/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReportRouteImport } from './routes/api.report'
import { Route as ApiLeaderboardRouteImport } from './routes/api.leaderboard'
import { Route as ApiVoteStateRouteImport } from './routes/api.vote.state'
import { Route as ApiVoteStartRouteImport } from './routes/api.vote.start'
import { Route as ApiVotePickRouteImport } from './routes/api.vote.pick'
import { Route as ApiVoteOptionsRouteImport } from './routes/api.vote.options'
import { Route as ApiAdminTrackRouteImport } from './routes/api.admin.track'
import { Route as ApiAdminSeedRouteImport } from './routes/api.admin.seed'
import { Route as ApiAdminElectoralListsRouteImport } from './routes/api.admin.electoral-lists'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteStateRoute = ApiVoteStateRouteImport.update({
  id: '/api/vote/state',
  path: '/api/vote/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteStartRoute = ApiVoteStartRouteImport.update({
  id: '/api/vote/start',
  path: '/api/vote/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotePickRoute = ApiVotePickRouteImport.update({
  id: '/api/vote/pick',
  path: '/api/vote/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoteOptionsRoute = ApiVoteOptionsRouteImport.update({
  id: '/api/vote/options',
  path: '/api/vote/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTrackRoute = ApiAdminTrackRouteImport.update({
  id: '/api/admin/track',
  path: '/api/admin/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedRoute = ApiAdminSeedRouteImport.update({
  id: '/api/admin/seed',
  path: '/api/admin/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminElectoralListsRoute = ApiAdminElectoralListsRouteImport.update({
  id: '/api/admin/electoral-lists',
  path: '/api/admin/electoral-lists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/duel': typeof DuelRoute
  '/results': typeof ResultsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/report': typeof ApiReportRoute
  '/api/admin/electoral-lists': typeof ApiAdminElectoralListsRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/track': typeof ApiAdminTrackRoute
  '/api/vote/options': typeof ApiVoteOptionsRoute
  '/api/vote/pick': typeof ApiVotePickRoute
  '/api/vote/start': typeof ApiVoteStartRoute
  '/api/vote/state': typeof ApiVoteStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/duel': typeof DuelRoute
  '/results': typeof ResultsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/report': typeof ApiReportRoute
  '/api/admin/electoral-lists': typeof ApiAdminElectoralListsRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/track': typeof ApiAdminTrackRoute
  '/api/vote/options': typeof ApiVoteOptionsRoute
  '/api/vote/pick': typeof ApiVotePickRoute
  '/api/vote/start': typeof ApiVoteStartRoute
  '/api/vote/state': typeof ApiVoteStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/classement': typeof ClassementRoute
  '/duel': typeof DuelRoute
  '/results': typeof ResultsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/report': typeof ApiReportRoute
  '/api/admin/electoral-lists': typeof ApiAdminElectoralListsRoute
  '/api/admin/seed': typeof ApiAdminSeedRoute
  '/api/admin/track': typeof ApiAdminTrackRoute
  '/api/vote/options': typeof ApiVoteOptionsRoute
  '/api/vote/pick': typeof ApiVotePickRoute
  '/api/vote/start': typeof ApiVoteStartRoute
  '/api/vote/state': typeof ApiVoteStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/classement'
    | '/duel'
    | '/results'
    | '/api/leaderboard'
    | '/api/report'
    | '/api/admin/electoral-lists'
    | '/api/admin/seed'
    | '/api/admin/track'
    | '/api/vote/options'
    | '/api/vote/pick'
    | '/api/vote/start'
    | '/api/vote/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/classement'
    | '/duel'
    | '/results'
    | '/api/leaderboard'
    | '/api/report'
    | '/api/admin/electoral-lists'
    | '/api/admin/seed'
    | '/api/admin/track'
    | '/api/vote/options'
    | '/api/vote/pick'
    | '/api/vote/start'
    | '/api/vote/state'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/classement'
    | '/duel'
    | '/results'
    | '/api/leaderboard'
    | '/api/report'
    | '/api/admin/electoral-lists'
    | '/api/admin/seed'
    | '/api/admin/track'
    | '/api/vote/options'
    | '/api/vote/pick'
    | '/api/vote/start'
    | '/api/vote/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ClassementRoute: typeof ClassementRoute
  DuelRoute: typeof DuelRoute
  ResultsRoute: typeof ResultsRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiAdminElectoralListsRoute: typeof ApiAdminElectoralListsRoute
  ApiAdminSeedRoute: typeof ApiAdminSeedRoute
  ApiAdminTrackRoute: typeof ApiAdminTrackRoute
  ApiVoteOptionsRoute: typeof ApiVoteOptionsRoute
  ApiVotePickRoute: typeof ApiVotePickRoute
  ApiVoteStartRoute: typeof ApiVoteStartRoute
  ApiVoteStateRoute: typeof ApiVoteStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote/state': {
      id: '/api/vote/state'
      path: '/api/vote/state'
      fullPath: '/api/vote/state'
      preLoaderRoute: typeof ApiVoteStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote/start': {
      id: '/api/vote/start'
      path: '/api/vote/start'
      fullPath: '/api/vote/start'
      preLoaderRoute: typeof ApiVoteStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote/pick': {
      id: '/api/vote/pick'
      path: '/api/vote/pick'
      fullPath: '/api/vote/pick'
      preLoaderRoute: typeof ApiVotePickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vote/options': {
      id: '/api/vote/options'
      path: '/api/vote/options'
      fullPath: '/api/vote/options'
      preLoaderRoute: typeof ApiVoteOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/track': {
      id: '/api/admin/track'
      path: '/api/admin/track'
      fullPath: '/api/admin/track'
      preLoaderRoute: typeof ApiAdminTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed': {
      id: '/api/admin/seed'
      path: '/api/admin/seed'
      fullPath: '/api/admin/seed'
      preLoaderRoute: typeof ApiAdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/electoral-lists': {
      id: '/api/admin/electoral-lists'
      path: '/api/admin/electoral-lists'
      fullPath: '/api/admin/electoral-lists'
      preLoaderRoute: typeof ApiAdminElectoralListsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ClassementRoute: ClassementRoute,
  DuelRoute: DuelRoute,
  ResultsRoute: ResultsRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiReportRoute: ApiReportRoute,
  ApiAdminElectoralListsRoute: ApiAdminElectoralListsRoute,
  ApiAdminSeedRoute: ApiAdminSeedRoute,
  ApiAdminTrackRoute: ApiAdminTrackRoute,
  ApiVoteOptionsRoute: ApiVoteOptionsRoute,
  ApiVotePickRoute: ApiVotePickRoute,
  ApiVoteStartRoute: ApiVoteStartRoute,
  ApiVoteStateRoute: ApiVoteStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
